src/App/Entity/Student.php
<?php

namespace App\Entity;

class Student
{
    /**
     * @var int
     */
    private $id;
    /**
     * @var string
     */
    private $firstName;
    /**
     * @var string
     */
    private $lastName;
    /**
     * @var StudentInfo
     */
    private $StudentInfo;
    /**
     * @var Clazz
     */
    private $Clazz;

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     */
    public function setFirstName( $firstName )
    {
        $this->firstName = $firstName;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     */
    public function setLastName( $lastName )
    {
        $this->lastName = $lastName;
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return StudentInfo
     */
    public function getStudentInfo()
    {
        return $this->StudentInfo;
    }

    /**
     * @param StudentInfo $StudentInfo
     */
    public function setStudentInfo( $StudentInfo )
    {
        $this->StudentInfo = $StudentInfo;
    }

    /**
     * @return Clazz
     */
    public function getClazz()
    {
        return $this->Clazz;
    }

    /**
     * @param Clazz $Clazz
     */
    public function setClazz( $Clazz )
    {
        $this->Clazz = $Clazz;
    }

    public function __toString()
    {
        return $this->getLastName() .' '. $this->getFirstName();
    }

}

src/App/Form/StudentType.php
<?php

namespace App\Form;

use Symfony\Component\Form\Extension\Core\Type as FormType;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints;
use App\Entity\Student;
use App\Entity\Clazz;

class StudentType extends AbstractType
{
    public function buildForm( FormBuilderInterface $builder , array $options )
    {
        $builder
            ->add( 'firstName' , FormType\TextType::class ,
                [
                    'label'         =>  'Jméno' ,
                    'required'      =>  true ,
                    'constraints'   =>
                        [
                            new Constraints\Length([ 'min' => 3 , 'max' => 10 ]) ,
                            new Constraints\NotBlank() ,
                        ]
                ])
            ->add( 'lastName' , FormType\TextType::class ,
                [
                    'label'         =>  'Příjmení' ,
                    'required'      =>  true ,
                    'constraints'   =>
                        [
                            new Constraints\Length([ 'min' => 3 , 'max' => 10 ]) ,
                            new Constraints\NotBlank() ,
                        ]
                ])
            ->add( 'Clazz' , EntityType::class ,
                [
                    'label'         =>  'Třída' ,
                    'required'      =>  false ,
                    'class'         =>  Clazz::class ,
                    'em'            =>  $options['em'] ,
                    'choice_label'  =>  'name' ,
                    'empty_data'    =>  null ,
                    'placeholder'   =>  '-' ,
                    'constraints'   =>
                        [
                            new Constraints\Valid() ,
                        ]
                ])
            ->add( 'StudentInfo' , StudentInfoType::class ,
                [
                    'label'         =>  'Info' ,
                    'required'      =>  false ,
                    'constraints'   =>
                        [
                            new Constraints\Valid() ,
                        ]
                ])
        ;
    }

    public function configureOptions( OptionsResolver $resolver )
    {
        $resolver->setDefaults(array(
            'data_class' => Student::class,
        ));

        $resolver->setRequired([ 'em' ]);
    }

}

src/App/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use Silex\ControllerCollection;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class StudentController extends \Core\AbstractController
{
    public function cgetAction()
    {
        //TODO: translations, studentInfo

//        $s1 =   $er->findBy([ 'firstName' => 'josef' ] , [ 'lastName' => 'asc' ]);
//        $s1 =   $er->findOneBy([ 'firstName' => 'josef' ]);

        /**
         * @var $em \Doctrine\ORM\EntityManagerInterface
         */
        $em =   $this->app['orm.em'];
        $er =   $em->getRepository( 'App\Entity\Student' );

        return $this->app->render( '/student/cget.html.twig' , [ 'students' => $er->findAll() ] );
    }

    public function cgetFreeAction()
    {
        $er         =   $this->getRepository();
//        $students   =   $er->findBy([ 'Clazz' => null ]);

        $qb         =   $er->createQueryBuilder( 's' );
        $qb
            ->where( 's.Clazz IS NULL' )
            ->orderBy( 's.lastName' , 'asc' )
//            ->where( "s.firstName = 'karel'" )
//            ->where( $qb->expr()->eq( 's.firstName' , $qb->expr()->literal( 'karel' ) ) )
        ;

        $students   =   $qb->getQuery()->getResult();

        return $this->app->render( '/student/cget.html.twig' , [ 'students' => $students ] );
    }

    public function cpostAction( Request $request )
    {
        $em     =   $this->app['orm.em'];
        $form   =   $this->app->form( new Student() , [ 'em' => $em ] , StudentType::class )->getForm();

        $form->submit( $request->request->get( 'student' ) );

        if( $form->isValid() )
        {
            $student    =   $form->getData();
            $info       =   $form->get( 'StudentInfo' )->getData();

            //protože StudentInfo je identifying relation, potřebuje ID Studenta
            //ten ho ale ještě nemá, není uložený
            //musíme prvně Student::$StudentInfo nastavit na null,
            //uložit studenta a tím vytvořit jeho ID
            //a pak vycucnout ID studenta přes EntityManager::refresh()
            //poté už nastavíme Student::$StudentInfo i StudentInfo::$Student
            //a uložíme podruhé

            if( $info )
            {
                $student->setStudentInfo( null );
                $info->setStudent( $student );

                $em->persist( $student );
                $em->flush();
                $em->refresh( $student );

                $student->setStudentInfo( $info );
                $info->setStudent( $student );

                $em->persist( $info );
            }

            $em->persist( $student );
            $em->flush();

            return $this->app->redirect( $this->app->url( 'get_students' ) )
                ->setStatusCode( Response::HTTP_CREATED );
        }
        else
        {
            return $this->app->render( '/student/new.html.twig' , [ 'form' => $form->createView() ] )
                ->setStatusCode( Response::HTTP_BAD_REQUEST );
        }
    }

    public function getAction( $student )
    {
        $student    =   $this->getRepository()->find( $student );

        return $this->app->render( '/student/get.html.twig' , [ 'student' => $student ] );
    }

    public function deleteAction( $student )
    {
        $student    =   $this->getRepository()->find( $student );
        $em         =   $this->app['orm.em'];

        if( $student->getStudentInfo() )
        {
            $em->remove( $student->getStudentInfo() );
        }

        $em->remove( $student );
        $em->flush();

        return $this->app->redirect( $this->app->url( 'get_students' ) );
    }

    public function putAction( $student , Request $request )
    {
        $em         =   $this->app['orm.em'];
        $student    =   $this->getRepository()->find( $student );
        $form       =   $this->app->form( $student , [ 'em' => $em ] , StudentType::class )->getForm();

        $form->submit( $request->request->get( 'student' ) );

        if( $form->isValid() )
        {
            $student    =   $form->getData();
            $info       =   $form->get( 'StudentInfo' )->getData();

            if( $info )
            {
                $student->setStudentInfo( $info );
                $info->setStudent( $student );
                $em->persist( $info );
            }

            $em->persist( $student ); //$form::getData() vrací instanci Student
            $em->flush();

            return $this->app->redirect( $this->app->url( 'get_students' ) );
        }
        else
        {
            return $this->app->render( '/student/edit.html.twig' , [ 'form' => $form->createView() ] )
                ->setStatusCode( Response::HTTP_BAD_REQUEST );
        }
    }

    public function newAction()
    {
        $form   =   $this->app->form( new Student() , [ 'em' => $this->app['orm.em'] ] , StudentType::class )->getForm();

        return $this->app->render( '/student/new.html.twig' , [ 'form' => $form->createView() ] );
    }

    public function editAction( $student )
    {
        $student    =   $this->getRepository()->find( $student );
        $form       =   $this->app->form( $student , [ 'em' => $this->app['orm.em'] ] , StudentType::class )->getForm();

        return $this->app->render( '/student/edit.html.twig' , [ 'form' => $form->createView() ] );
    }

    public function removeAction( $student )
    {
        $student    =   $this->getRepository()->find( $student );

        return $this->app->render( '/student/remove.html.twig' , [ 'student' => $student ] );
    }

    /**
     * @return \Doctrine\ORM\EntityRepository
     */
    protected function getRepository()
    {
        return $this->app['orm.em']->getRepository( 'App\Entity\Student' );
    }

    protected function createForm()
    {
        //sestavíme fb
        //vrátíme fb nebo form
        return $this->app->form( new Student() , [] , StudentType::class );
    }

    protected function connect( ControllerCollection $controllers )
    {
        //http://www.restapitutorial.com/lessons/httpmethods.html

        $controllers
            ->get( '/' , [ $this , 'cgetAction' ] )
            ->bind( 'get_students' )
        ;

        $controllers
            ->get( '/free' , [ $this , 'cgetFreeAction' ] )
            ->bind( 'get_free_students' )
        ;

        $controllers
            ->post( '/' , [ $this , 'cpostAction' ] )
            ->bind( 'post_students' )
        ;

        $controllers
            ->get( '/new' , [ $this , 'newAction' ] )
            ->bind( 'new_student' )
        ;

        $controllers
            ->get( '/{student}' , [ $this , 'getAction' ] )
            ->bind( 'get_student' )
        ;

        $controllers
            ->put( '/{student}' , [ $this , 'putAction' ] )
            ->bind( 'put_student' )
        ;

        $controllers
            ->delete( '/{student}' , [ $this , 'deleteAction' ] )
            ->bind( 'delete_student' )
        ;

        $controllers
            ->get( '/{student}/edit' , [ $this , 'editAction' ] )
            ->bind( 'edit_student' )
        ;

        $controllers
            ->get( '/{student}/remove' , [ $this , 'removeAction' ] )
            ->bind( 'remove_student' )
        ;

        return $controllers;
    }
}

src/Resources/views/student/cget.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ app.user | default( 'nepřihlášený' ) }}

    <a href="{{ url( 'new_student' ) }}">přidat</a>

    <table>
        <thead>
            <tr>
                <th>jméno</th>
                <th>příjmení</th>
                <th>třída</th>
                <th>upravit</th>
                <th>smazat</th>
                <th>detail</th>
            </tr>
        </thead>

        <tbody>
        {% for student in students %}
            <tr>
                <td>{{ student.firstName }}</td> {# firstName -> getFirstName #}
                <td>{{ student.lastName }}</td>
                <td>{{ student.clazz ? student.clazz.name : "x" }}</td>
                <td>
                    <a href="{{ url( 'edit_student' , { 'student' : student.id } ) }}">upravit</a>
                </td>
                <td>
                    <a href="{{ url( 'remove_student' , { 'student' : student.id } ) }}">smazat</a>
                </td>
                <td>
                    <a href="{{ url( 'get_student' , { 'student' : student.id } ) }}">detail</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock body %}

src/Resources/views/student/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form_start( form , { 'method' : 'PUT' , 'action' : url( 'put_student' , { 'student' : global.request.attributes.get( 'student' ) } ) } ) }}

    {% include '/student/form.html.twig' %}

    <button type="submit">upravit</button>

    {{ form_end( form ) }}

{% endblock body %}

src/Resources/views/student/form.html.twig
<table>
    <tr>
        <th>{{ form_label( form.firstName ) }}</th>
        <td>{{ form_widget( form.firstName , { 'attr' : { 'placeholder' : form.firstName.vars.label } } ) }}</td>
        <td>{{ form_errors( form.firstName ) }}</td>
    </tr>
    <tr>
        <th>{{ form_label( form.lastName ) }}</th>
        <td>{{ form_widget( form.lastName , { 'attr' : { 'placeholder' : form.lastName.vars.label } } ) }}</td>
        <td>{{ form_errors( form.lastName ) }}</td>
    </tr>
    <tr>
        <th>{{ form_label( form.Clazz ) }}</th>
        <td>{{ form_widget( form.Clazz ) }}</td>
        <td>{{ form_errors( form.Clazz ) }}</td>
    </tr>
</table>

src/Resources/views/student/get.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <table>
        <tr>
            <th>Jméno</th>
            <td>{{ student.firstName }}</td>
        </tr>
        <tr>
            <th>Příjmení</th>
            <td>{{ student.lastName }}</td>
        </tr>
        <tr>
            <th>Třída</th>
            <td>{{ student.Clazz ? student.Clazz.name : 'x' }}</td>
        </tr>

        {% if student.StudentInfo is not null %}
            <tr>
                <th>Email</th>
                <td>{{ student.StudentInfo.email }}</td>
            </tr>
            <tr>
                <th>Telefon</th>
                <td>{{ student.StudentInfo.phone }}</td>
            </tr>
        {% endif %}

    </table>

{% endblock body %}

src/Resources/views/student/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form_start( form , { 'method' : 'POST' , 'action' : url( 'post_students' ) } ) }}

    {% include '/student/form.html.twig' %}

    <button type="submit">přidat</button>

    {{ form_end( form ) }}

{% endblock body %}

src/Resources/views/student/remove.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    Opravdu smazat studenta
    <strong>{{ student.firstName }}</strong>
    <strong>{{ student.lastName }}</strong>
    ?

    <form method="post" action="{{ url( 'delete_student' , { 'student' : global.request.attributes.get( 'student' ) } ) }}">
        <input type="hidden" name="_method" value="DELETE" />
        <button type="submit">Ano</button>
        <button type="button" onclick="location.assign( '{{ url( 'get_students' ) }}' )">Ne</button>
    </form>

{% endblock body %}