src/App/Entity/Clazz.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

class Clazz
{
    /**
     * @var int
     */
    private $id;
    /**
     * @var string
     */
    private $name;
    /**
     * @var Collection
     */
    private $Students;
    /**
     * @var Collection
     */
    private $Teachers;

    public function __construct()
    {
        $this->Students =   new ArrayCollection();
        $this->Teachers =   new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName( $name )
    {
        $this->name = $name;
    }

    /**
     * @return Collection
     */
    public function getStudents()
    {
        return $this->Students;
    }

    /**
     * @return Collection
     */
    public function getTeachers()
    {
        return $this->Teachers;
    }

}

src/Resources/views/class/cget.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <a href="{{ url( 'new_class' ) }}">přidat</a>

    <table>
        <thead>
            <tr>
                <th>název</th>
                <th>studentů</th>
                <th>učitelů</th>
                <th>upravit</th>
                <th>smazat</th>
                <th>detail</th>
            </tr>
        </thead>

        <tbody>
        {% for class in classes %}
            <tr>
                <td>{{ class.name }}</td> {# firstName -> getFirstName #}
                <td>{{ class.students.count }}</td>
                <td>{{ class.teachers.count }}</td>
                <td>
                    <a href="{{ url( 'edit_class' , { 'class' : class.id } ) }}">upravit</a>
                </td>
                <td>
                    <a href="{{ url( 'remove_class' , { 'class' : class.id } ) }}">smazat</a>
                </td>
                <td>
                    <a href="{{ url( 'get_class' , { 'class' : class.id } ) }}">detail</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock body %}

src/Resources/views/class/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form_start( form , { 'method' : 'PUT' , 'action' : url( 'put_class' , { 'class' : global.request.attributes.get( 'class' ) } ) } ) }}

    {% include '/class/form.html.twig' %}

    <button type="submit">upravit</button>

    {{ form_end( form ) }}

{% endblock body %}

src/Resources/views/class/form.html.twig
<table>
    <tr>
        <th>{{ form_label( form.name ) }}</th>
        <td>{{ form_widget( form.name , { 'attr' : { 'placeholder' : form.name.vars.label } } ) }}</td>
        <td>{{ form_errors( form.name ) }}</td>
    </tr>
    <tr>
        <th>{{ form_label( form.Students ) }}</th>
        <td>{{ form_widget( form.Students ) }}</td>
        <td>{{ form_errors( form.Students ) }}</td>
    </tr>
    <tr>
        <th>{{ form_label( form.Teachers ) }}</th>
        <td>{{ form_widget( form.Teachers ) }}</td>
        <td>{{ form_errors( form.Teachers ) }}</td>
    </tr>
</table>

src/Resources/views/class/get.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <table>
        <tr>
            <th>Název</th>
            <td>{{ class.name }}</td>
        </tr>
        <tr>
            <th>Počet studentů</th>
            <td>{{ class.Students.count }}</td>
        </tr>
        <tr>
            <th>Počet učitelů</th>
            <td>{{ class.Teachers.count }}</td>
        </tr>

    </table>

{% endblock body %}

src/Resources/views/class/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {{ form_start( form , { 'method' : 'POST' , 'action' : url( 'post_classes' ) } ) }}

    {% include '/class/form.html.twig' %}

    <button type="submit">přidat</button>

    {{ form_end( form ) }}

{% endblock body %}

src/Resources/views/class/remove.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    Opravdu smazat třídu
    <strong>{{ class.name }}</strong> , která obsahuje
    <strong>{{ class.Students.count }}</strong>  studentů
    ?

    <form method="post" action="{{ url( 'delete_class' , { 'class' : global.request.attributes.get( 'class' ) } ) }}">
        <input type="hidden" name="_method" value="DELETE" />
        <button type="submit">Ano</button>
        <button type="button" onclick="location.assign( '{{ url( 'get_classes' ) }}' )">Ne</button>
    </form>

{% endblock body %}